spring.application.name=pma

spring.datasource.url=jdbc:postgresql://aws-0-ap-northeast-1.pooler.supabase.com:5432/postgres
spring.datasource.username=postgres.fkxtdgmiemcwcegnpnti
spring.datasource.password=${DB_PASSWORD}

spring.jpa.hibernate.ddl-auto=update

app.jwt.secret=${JWT_SECRET}
app.jwt.expiration=900000
app.encryption.key=${APP_ENCRYPTION_KEY}

spring.mail.host=smtp.ethereal.email
spring.mail.port=587
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
app.mail.from=noreply@vault.local

app.otp.expiration-minutes=3
app.otp.max-attempts=3
app.otp.resend-cooldown-seconds=60